### ISSUE TITLE
Make DirectCounterMaxElements configurable

### ISSUE THREAD

**Issue by upasnarayan** [saguiitay/CardinalityEstimation#18]
Would be great to be able to change the 100 direct counter elements to something smaller, like 10 or 20. Maybe a parameter in the constructor like the # of bits to use. We are working on a project with a significant memory restriction and so we want to reduce the amount of storage used as much as possible.

**Comment by oronnavon** [comment]
Seems to me that if you're really trying to save memory, then you'd be better server by just removing the HashSet altogether, rather than constraining it to fewer elements - it only serves to keep 100% accurate counts, which you might not need.  There are also other, better savings to be had, for example by saving the array of rho's in a more compact way, as each rho has an upper bound of log2(64) or less, so they don't use 8 bits in practice - the current implementation wastes lots of space there.  You could also save a compressed representation of the same array, or a variable-length encoding of the rho's.  But overall, this library would not be the first place I would look for memory savings (if memory is really that tight, should you be using C# in the first place?)

In any case, you are welcome to fork the project and customize as you like.

Best,
Oron

**Comment by upasnarayan** [comment]
Thanks Oron for your thoughts. After evaluation, I do think that having the 100 direct counter elements is useful for our project to have 100% accurate counts for small volume cases. This library seems to be the best out there in terms of accuracy and ease of use, so we are going to try to use this nuget package in our project.
